import Database from 'better-sqlite3';
import { dirname } from 'path';
import { config, ensureDirExists } from '../config';
import { runMigrations } from '../migrations';
import { logger } from '../logger';
import { ensureAutoGeneratedCredentials } from '../auto-credentials';
import { seedAdminUserFromEnv } from './seed';

const DB_PATH = config.dbPath;

export const isBuildPhase = process.env.NEXT_PHASE === 'phase-production-build';
export const isTestMode = process.env.MISSION_CONTROL_TEST_MODE === '1';

/**
 * Validates required environment variables at boot time.
 * Logs prominent warnings instead of throwing — the /setup wizard handles
 * the no-credentials case gracefully, and we don't want to crash on first run.
 */
export function validateRequiredEnv(): void {
  const hasAuthPass = !!(process.env.AUTH_PASS?.trim())
  const hasAuthPassB64 = !!(process.env.AUTH_PASS_B64?.trim())

  if (!hasAuthPass && !hasAuthPassB64) {
    // Not a fatal error — /setup wizard will create the first user instead
    logger.warn(
      '[ENV] Neither AUTH_PASS nor AUTH_PASS_B64 is set. ' +
      'The admin account will not be seeded from env. ' +
      'Use the /setup wizard to create your first user, or set AUTH_PASS in .env.'
    )
  }

  const dbPathOverride = process.env.MISSION_CONTROL_DB_PATH
  if (dbPathOverride) {
    const { existsSync, accessSync, constants } = require('fs') as typeof import('fs')
    const { dirname: resolveDirname } = require('path') as typeof import('path')
    const dir = resolveDirname(dbPathOverride)
    if (!existsSync(dir)) {
      logger.warn(
        `[ENV] MISSION_CONTROL_DB_PATH is set to "${dbPathOverride}" but the directory "${dir}" does not exist. ` +
        'The database will fail to open. Create the directory or correct the path in .env.'
      )
    } else {
      try {
        accessSync(dir, constants.W_OK)
      } catch {
        logger.warn(
          `[ENV] MISSION_CONTROL_DB_PATH directory "${dir}" exists but is not writable by this process. ` +
          'Check filesystem permissions.'
        )
      }
    }
  }
}

// Global database instance — module-level singleton
let db: Database.Database | null = null;

// WHY: tracked separately so dynamic imports (webhooks, scheduler) only fire once
// across hot-reloads in Next.js dev mode.
let webhookListenerInitialized = false;

function initializeSchema(): void {
  if (!db) return;
  try {
    runMigrations(db);
    seedAdminUserFromEnv(db);
    // WHY: ECC instincts are pre-validated, high-confidence patterns that bootstrap
    // the self-learning engine without requiring Ultron to learn them from scratch.
    // Called after migrations so learned_patterns table is guaranteed to exist.
    import('../seeds/ecc-instincts').then(({ seedECCInstincts }) => {
      seedECCInstincts();
    }).catch((err) => {
      logger.warn({ err }, 'ECC instinct seeding skipped — non-fatal');
    });

    if (!webhookListenerInitialized) {
      webhookListenerInitialized = true;
      import('../webhooks').then(({ initWebhookListener }) => {
        initWebhookListener();
      }).catch(() => {
        // Silent - webhooks are optional
      });

      // Start built-in scheduler for runtime installs only.
      // Skip during `next build` and E2E/test mode to keep startup deterministic.
      if (!isBuildPhase && !isTestMode) {
        import('../scheduler').then(({ initScheduler }) => {
          initScheduler();
        }).catch(() => {
          // Silent - scheduler is optional
        });
      }
    }

    if (!isBuildPhase) {
      logger.info('Database migrations applied successfully');
    }
  } catch (error) {
    logger.error({ err: error }, 'Failed to apply database migrations');
    throw error;
  }
}

/**
 * Get or create the module-level database connection.
 * Lazily opens the file, enables WAL mode, and runs migrations on first call.
 */
export function getDatabase(): Database.Database {
  if (!db) {
    ensureAutoGeneratedCredentials();
    ensureDirExists(dirname(DB_PATH));
    db = new Database(DB_PATH);

    // Enable WAL mode for better concurrent access
    db.pragma('journal_mode = WAL');
    db.pragma('synchronous = NORMAL');
    db.pragma('cache_size = 1000');
    db.pragma('foreign_keys = ON');
    // Retry for up to 5 s before throwing SQLITE_BUSY; prevents contention
    // errors under concurrent Next.js route-handler requests.
    db.pragma('busy_timeout = 5000');

    initializeSchema();
  }

  return db;
}

/**
 * Close database connection (used for graceful shutdown and tests).
 */
export function closeDatabase(): void {
  if (db) {
    db.close();
    db = null;
  }
}

// Initialize database on module load — skip during `next build` to prevent
// build-time vs runtime SQLite state conflicts (SQLITE_BUSY on cold start).
if (typeof window === 'undefined' && !isBuildPhase) {
  // Validate env vars before opening the DB so any misconfiguration is
  // surfaced immediately in the server console on cold start.
  validateRequiredEnv();
  try {
    getDatabase();
  } catch (error) {
    logger.error({ err: error }, 'Failed to initialize database');
  }
}

/**
 * Returns true when the database has zero users — i.e. first-time setup is needed.
 * Safe to call during normal operation (fast single-row query).
 */
export function needsFirstTimeSetup(): boolean {
  try {
    const database = getDatabase()
    const row = database.prepare('SELECT COUNT(*) as count FROM users').get() as { count: number }
    return row.count === 0
  } catch {
    return false
  }
}

// Cleanup on process exit
process.on('exit', closeDatabase);
process.on('SIGINT', closeDatabase);
process.on('SIGTERM', closeDatabase);
