// Barrel export for the office panel sub-components.
// Import from '@/components/panels/office' to get all public exports.

export * from './office-types'
export * from './office-utils'
export * from './office-map-constants'
export { OfficeSidebar } from './office-sidebar'
export { OfficeMapCanvas } from './office-map-canvas'
export { OfficeMinimap } from './office-minimap'
export { OfficeDeckLog } from './office-deck-log'
export { OrgChart } from './org-chart'
export { AgentModal } from './agent-modal'
export { FlightDeckModal } from './flight-deck-modal'
export { OfficeLaunchToast } from './office-launch-toast'
export { useThemePalette } from './use-theme-palette'
export { useOfficeSeatMap } from './use-office-seat-map'
export { useOrgGroups } from './use-org-groups'
export { useOfficePrefs } from './use-office-prefs'
export { useOfficeAgents } from './use-office-agents'
export type { UseOfficeAgentsOutput } from './use-office-agents'
export { useOfficeAnimations } from './use-office-animations'
export type { UseOfficeAnimationsOutput } from './use-office-animations'
export { OfficeHeader } from './office-header'
export { OfficeEmptyState } from './office-empty-state'
export { OfficeMapStyles } from './office-map-styles'
