import { NextResponse } from 'next/server'
import { apiGuard } from '@/lib/api-guard'
import { isJarvisEnabled } from '@/lib/jarvis/config'
import * as fs from 'fs'
import * as path from 'path'

/**
 * Returns the Jarvis auth token to authenticated Ultron users.
 *
 * The token is needed to establish the WebSocket connection to Jarvis.
 * We expose it via a server-side route so it never needs to be baked into
 * a NEXT_PUBLIC_ env var (which would be visible in the JS bundle).
 *
 * Token resolution order:
 *   1. JARVIS_AUTH_TOKEN env var (set in system env or Ultron .env)
 *   2. Token parsed from src/jarvis/.env (auto-generated by Jarvis on first run)
 */
function resolveJarvisToken(): string | null {
  // 1. System/Ultron env var
  const envToken = process.env.JARVIS_AUTH_TOKEN?.trim()
  if (envToken) return envToken

  // 2. Read from the Jarvis .env file that server.py auto-generates
  try {
    const jarvisEnvPath = path.join(process.cwd(), 'src', 'jarvis', '.env')
    if (!fs.existsSync(jarvisEnvPath)) return null

    const contents = fs.readFileSync(jarvisEnvPath, 'utf-8')
    for (const line of contents.split('\n')) {
      const trimmed = line.trim()
      if (!trimmed || trimmed.startsWith('#')) continue
      const eqIdx = trimmed.indexOf('=')
      if (eqIdx === -1) continue
      const key = trimmed.slice(0, eqIdx).trim()
      if (key === 'JARVIS_AUTH_TOKEN') {
        return trimmed.slice(eqIdx + 1).trim().replace(/^["']|["']$/g, '')
      }
    }
  } catch {
    // File unreadable — fall through
  }

  return null
}

export const GET = apiGuard({ role: 'viewer', rateLimit: 'read' }, async () => {
  if (!isJarvisEnabled()) {
    return NextResponse.json({ error: 'JARVIS is disabled' }, { status: 503 })
  }

  const token = resolveJarvisToken()
  if (!token) {
    return NextResponse.json(
      { error: 'JARVIS auth token not found. Start the Jarvis server first.' },
      { status: 404 }
    )
  }

  return NextResponse.json({ token })
})
