#!/usr/bin/env bash
# ============================================================
# JARVIS — First-time setup
# Run once from the src/jarvis/ directory:  bash setup.sh
# ============================================================
set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

RED='\033[0;31m'; GREEN='\033[0;32m'; CYAN='\033[0;36m'
YELLOW='\033[1;33m'; BOLD='\033[1m'; NC='\033[0m'

banner() { echo -e "\n${CYAN}${BOLD}▸ $1${NC}\n"; }
ok()     { echo -e "${GREEN}✓${NC} $1"; }
warn()   { echo -e "${YELLOW}⚠${NC}  $1"; }
err()    { echo -e "${RED}✗${NC} $1"; }

echo -e "\n${BOLD}${CYAN}JARVIS Setup${NC}"
echo "────────────────────────────────────────"

# ── 1. Read existing .env values as defaults ───────────────────────────────
if [[ -f .env ]]; then
  warn ".env already exists — values will be used as defaults."
  source .env 2>/dev/null || true
fi

# ── 2. Anthropic API key ───────────────────────────────────────────────────
banner "Anthropic API Key"
echo "Required for JARVIS to talk to Claude."
echo "Get one at: https://console.anthropic.com"
echo ""
current_key="${ANTHROPIC_API_KEY:-}"
if [[ -n "$current_key" ]]; then
  masked="${current_key:0:12}...${current_key: -4}"
  read -rp "  API key [$masked]: " input_key
  ANTHROPIC_API_KEY="${input_key:-$current_key}"
else
  read -rp "  API key: " ANTHROPIC_API_KEY
  while [[ -z "$ANTHROPIC_API_KEY" ]]; do
    err "API key is required."
    read -rp "  API key: " ANTHROPIC_API_KEY
  done
fi
ok "Anthropic API key set."

# ── 3. TTS Engine ─────────────────────────────────────────────────────────
banner "Text-to-Speech Engine"
echo "  1) edge  — Free Microsoft Edge TTS (no extra key needed)"
echo "  2) fish  — Premium Fish Audio (realistic MCU JARVIS voice)"
echo ""
current_tts="${TTS_ENGINE:-edge}"
read -rp "  Choose [edge/fish] (default: $current_tts): " input_tts
TTS_ENGINE="${input_tts:-$current_tts}"
if [[ "$TTS_ENGINE" != "edge" && "$TTS_ENGINE" != "fish" ]]; then
  warn "Unknown engine '$TTS_ENGINE', defaulting to edge."
  TTS_ENGINE="edge"
fi
ok "TTS engine: $TTS_ENGINE"

# ── 4. Fish Audio key (only if needed) ────────────────────────────────────
FISH_API_KEY="${FISH_API_KEY:-}"
FISH_VOICE_ID="${FISH_VOICE_ID:-612b878b113047d9a770c069c8b4fdfe}"

if [[ "$TTS_ENGINE" == "fish" ]]; then
  banner "Fish Audio API Key"
  echo "Get one at: https://fish.audio (Settings → API Keys)"
  if [[ -n "$FISH_API_KEY" ]]; then
    masked="${FISH_API_KEY:0:8}..."
    read -rp "  Fish API key [$masked]: " input_fish
    FISH_API_KEY="${input_fish:-$FISH_API_KEY}"
  else
    read -rp "  Fish API key: " FISH_API_KEY
    if [[ -z "$FISH_API_KEY" ]]; then
      warn "No Fish API key provided — falling back to edge TTS."
      TTS_ENGINE="edge"
    fi
  fi
  [[ -n "$FISH_API_KEY" ]] && ok "Fish API key set."
fi

# ── 5. Username personalisation ────────────────────────────────────────────
banner "Personalisation"
current_name="${USER_NAME:-sir}"
read -rp "  What should JARVIS call you? [$current_name]: " input_name
USER_NAME="${input_name:-$current_name}"
ok "JARVIS will address you as: $USER_NAME"

# ── 6. Write .env ─────────────────────────────────────────────────────────
banner "Writing .env"
cat > .env <<EOF
# Generated by setup.sh — $(date)
ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
TTS_ENGINE=${TTS_ENGINE}
FISH_API_KEY=${FISH_API_KEY}
FISH_VOICE_ID=${FISH_VOICE_ID}
USER_NAME=${USER_NAME}
JARVIS_PORT=${JARVIS_PORT:-8340}
EOF
ok ".env written."

# ── 7. Python dependencies ────────────────────────────────────────────────
banner "Installing Python dependencies"
if ! command -v python3 &>/dev/null; then
  err "python3 not found. Please install Python 3.11+."
  exit 1
fi
PYTHON_VERSION=$(python3 -c "import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}')")
echo "  Python $PYTHON_VERSION detected."

# Create venv if missing
if [[ ! -d .venv ]]; then
  python3 -m venv .venv
  ok "Created virtual environment."
fi

# shellcheck disable=SC1091
source .venv/bin/activate
pip install --quiet --upgrade pip
pip install --quiet -r requirements.txt
ok "Python packages installed."

# Install Playwright browsers (required for browser automation)
if python3 -c "import playwright" 2>/dev/null; then
  echo "  Installing Playwright browsers..."
  python3 -m playwright install chromium --quiet 2>/dev/null || warn "Playwright browser install skipped."
fi

# ── 8. Node / frontend dependencies ──────────────────────────────────────
banner "Installing Node dependencies"
FRONTEND_DIR="$SCRIPT_DIR/frontend"

if ! command -v node &>/dev/null; then
  warn "node not found — skipping frontend build. Install Node 18+ to build the UI."
else
  NODE_VERSION=$(node -v)
  echo "  Node $NODE_VERSION detected."
  cd "$FRONTEND_DIR"
  if command -v pnpm &>/dev/null; then
    pnpm install --silent
  elif command -v npm &>/dev/null; then
    npm install --silent
  fi
  ok "Node packages installed."
  cd "$SCRIPT_DIR"
fi

# ── 9. Build frontend ─────────────────────────────────────────────────────
banner "Building frontend"
if command -v node &>/dev/null; then
  cd "$FRONTEND_DIR"
  if command -v pnpm &>/dev/null; then
    pnpm run build 2>&1 | tail -5
  else
    npm run build 2>&1 | tail -5
  fi
  ok "Frontend built → frontend/dist/"
  cd "$SCRIPT_DIR"
else
  warn "Skipped (Node not found). Run 'npm run build' in frontend/ when Node is installed."
fi

# ── Done ─────────────────────────────────────────────────────────────────
echo ""
echo -e "${BOLD}${GREEN}Setup complete!${NC}"
echo "────────────────────────────────────────"
echo "  Start JARVIS with:  bash start.sh"
echo "  Then open:          http://localhost:${JARVIS_PORT:-9000}"
echo ""
