/**
 * Extended unit tests for auth.ts.
 * WHY: The existing auth.test.ts only covers safeCompare and requireRole (API-key path).
 * This file adds coverage for authenticateUser, createSession, validateSession,
 * destroySession, destroyAllUserSessions, getUserById, createUser, updateUser,
 * deleteUser, registerAuthResolver, and getUserFromRequest (session + proxy paths).
 */
import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest'

// ── Hoisted mock primitives ──────────────────────────────────────────────────
const { mockRun, mockGet, mockAll, mockPrepare, mockBroadcast } = vi.hoisted(() => {
  const mockRun = vi.fn(() => ({ lastInsertRowid: 1, changes: 1 }))
  const mockGet = vi.fn((): any => undefined)
  const mockAll = vi.fn((): any[] => [])
  const mockPrepare = vi.fn(() => ({ run: mockRun, get: mockGet, all: mockAll }))
  const mockBroadcast = vi.fn()
  return { mockRun, mockGet, mockAll, mockPrepare, mockBroadcast }
})

vi.mock('better-sqlite3', () => ({
  default: vi.fn(() => ({
    pragma: vi.fn(),
    prepare: mockPrepare,
    exec: vi.fn(),
    close: vi.fn(),
  })),
}))

vi.mock('@/lib/config', () => ({
  config: { dbPath: ':memory:' },
  ensureDirExists: vi.fn(),
}))

vi.mock('@/lib/migrations', () => ({ runMigrations: vi.fn() }))

vi.mock('@/lib/password', () => ({
  hashPassword: vi.fn((p: string) => `hashed:${p}`),
  // WHY: mock checks the plain-text password (first arg), not the stored hash,
  // because the actual scrypt comparison is irrelevant in unit tests.
  verifyPassword: vi.fn((pw: string, _hash: string) => pw === 'correct-password'),
}))

vi.mock('@/lib/logger', () => ({
  logger: { info: vi.fn(), error: vi.fn(), warn: vi.fn(), debug: vi.fn() },
}))

vi.mock('@/lib/event-bus', () => ({
  eventBus: { broadcast: mockBroadcast, on: vi.fn(), emit: vi.fn() },
}))

vi.mock('@/lib/auto-credentials', () => ({
  ensureAutoGeneratedCredentials: vi.fn(),
}))

vi.mock('@/lib/security-events', () => ({
  logSecurityEvent: vi.fn(),
}))

vi.mock('@/lib/session-cookie', () => ({
  parseMcSessionCookieHeader: vi.fn((header: string) => {
    // Extracts mc_session=<token> from a cookie string
    const match = header.match(/mc_session=([^;]+)/)
    return match ? match[1] : null
  }),
}))

vi.mock('@/lib/seeds/ecc-instincts', () => ({ seedECCInstincts: vi.fn() }))
vi.mock('@/lib/webhooks', () => ({ initWebhookListener: vi.fn() }))
vi.mock('@/lib/scheduler', () => ({ initScheduler: vi.fn() }))

import {
  authenticateUser,
  createSession,
  validateSession,
  destroySession,
  destroyAllUserSessions,
  getUserById,
  createUser,
  updateUser,
  deleteUser,
  registerAuthResolver,
  getUserFromRequest,
  requireRole,
  safeCompare,
  type User,
} from '@/lib/auth'

// ── Helpers ──────────────────────────────────────────────────────────────────

function makeUser(overrides: Partial<User> = {}): User {
  return {
    id: 1,
    username: 'testuser',
    display_name: 'Test User',
    role: 'operator',
    workspace_id: 1,
    tenant_id: 1,
    provider: 'local',
    email: null,
    avatar_url: null,
    is_approved: 1,
    created_at: 1000,
    updated_at: 1000,
    last_login_at: null,
    ...overrides,
  }
}

function makeDbUserRow(overrides: Record<string, any> = {}): Record<string, any> {
  return {
    id: 1,
    username: 'testuser',
    display_name: 'Test User',
    password_hash: 'hashed:correct-password',
    role: 'operator',
    workspace_id: 1,
    provider: 'local',
    provider_user_id: null,
    email: null,
    avatar_url: null,
    is_approved: 1,
    approved_by: null,
    approved_at: null,
    created_at: 1000,
    updated_at: 1000,
    last_login_at: null,
    ...overrides,
  }
}

function makeRequest(headers: Record<string, string> = {}): Request {
  return new Request('http://localhost/api/test', {
    headers: new Headers(headers),
  })
}

// ── authenticateUser ─────────────────────────────────────────────────────────
describe('authenticateUser', () => {
  beforeEach(() => {
    vi.clearAllMocks()
    // Default: seedAdminUserFromEnv calls COUNT(*) on init — return non-zero to skip seeding
    mockGet.mockReturnValue({ count: 1 })
  })

  it('returns null when user does not exist', () => {
    // First call is COUNT(*) for seed check, second is the actual user lookup
    mockGet.mockReturnValueOnce({ count: 1 }).mockReturnValue(undefined)
    const result = authenticateUser('ghost', 'anypass')
    expect(result).toBeNull()
  })

  it('returns null for non-local provider (prevents password bypass)', () => {
    mockGet.mockReturnValueOnce(makeDbUserRow({ provider: 'google' }))
    const result = authenticateUser('testuser', 'correct-password')
    expect(result).toBeNull()
  })

  it('returns null when user is not approved', () => {
    mockGet.mockReturnValueOnce(makeDbUserRow({ is_approved: 0 }))
    const result = authenticateUser('testuser', 'correct-password')
    expect(result).toBeNull()
  })

  it('returns null when password is wrong', () => {
    mockGet.mockReturnValueOnce(makeDbUserRow())
    // verifyPassword mock returns false for anything except 'hashed:correct-password'
    const result = authenticateUser('testuser', 'wrong-password')
    expect(result).toBeNull()
  })

  it('returns user object on valid credentials', () => {
    mockGet.mockReturnValueOnce(makeDbUserRow())
      .mockReturnValue({ tenant_id: 1 }) // workspace query
    const result = authenticateUser('testuser', 'correct-password')
    expect(result).not.toBeNull()
    expect(result!.username).toBe('testuser')
    expect(result!.role).toBe('operator')
  })

  it('falls back to local provider when provider field is null', () => {
    mockGet.mockReturnValueOnce(makeDbUserRow({ provider: null }))
      .mockReturnValue({ tenant_id: 1 })
    const result = authenticateUser('testuser', 'correct-password')
    expect(result).not.toBeNull()
    expect(result!.provider).toBe('local')
  })

  it('defaults is_approved to 1 when field is null', () => {
    mockGet.mockReturnValueOnce(makeDbUserRow({ is_approved: null }))
      .mockReturnValue({ tenant_id: 1 })
    const result = authenticateUser('testuser', 'correct-password')
    // is_approved null → treated as 1 → should succeed
    expect(result).not.toBeNull()
  })
})

// ── createSession ────────────────────────────────────────────────────────────
describe('createSession', () => {
  beforeEach(() => {
    vi.clearAllMocks()
    // workspace_id lookup for user, tenant lookup for workspace
    mockGet.mockReturnValue({ workspace_id: 1, tenant_id: 1 })
  })

  it('returns a hex token and future expiresAt', () => {
    const { token, expiresAt } = createSession(1)
    expect(token).toMatch(/^[0-9a-f]{64}$/)
    expect(expiresAt).toBeGreaterThan(Math.floor(Date.now() / 1000))
  })

  it('expiresAt is approximately 7 days from now', () => {
    const { expiresAt } = createSession(1)
    const sevenDays = 7 * 24 * 60 * 60
    const now = Math.floor(Date.now() / 1000)
    expect(expiresAt).toBeGreaterThanOrEqual(now + sevenDays - 5)
    expect(expiresAt).toBeLessThanOrEqual(now + sevenDays + 5)
  })

  it('calls INSERT on user_sessions and UPDATE on users', () => {
    createSession(42, '10.0.0.1', 'test-agent')
    // Two prepare().run calls: INSERT session + UPDATE last_login + DELETE expired
    expect(mockRun).toHaveBeenCalledTimes(3)
  })

  it('generates a different token each call', () => {
    const { token: t1 } = createSession(1)
    const { token: t2 } = createSession(1)
    expect(t1).not.toBe(t2)
  })
})

// ── validateSession ──────────────────────────────────────────────────────────
describe('validateSession', () => {
  beforeEach(() => {
    vi.clearAllMocks()
    mockGet.mockReturnValue({ tenant_id: 1 })
  })

  it('returns null for empty/falsy token', () => {
    expect(validateSession('')).toBeNull()
    expect(validateSession(null as any)).toBeNull()
  })

  it('returns null when session not found in DB', () => {
    mockGet.mockReturnValue(undefined)
    expect(validateSession('nonexistent-token')).toBeNull()
  })

  it('returns user+sessionId when session is valid', () => {
    const row = {
      id: 5,
      username: 'alice',
      display_name: 'Alice',
      role: 'admin' as const,
      provider: 'local' as const,
      email: null,
      avatar_url: null,
      is_approved: 1,
      workspace_id: 1,
      tenant_id: 1,
      created_at: 1000,
      updated_at: 1000,
      last_login_at: null,
      session_id: 99,
    }
    mockGet.mockReturnValue(row)
    const result = validateSession('valid-token')
    expect(result).not.toBeNull()
    expect(result!.username).toBe('alice')
    expect(result!.sessionId).toBe(99)
    expect(result!.role).toBe('admin')
  })

  it('defaults provider to "local" when null in DB', () => {
    const row = {
      id: 5, username: 'bob', display_name: 'Bob', role: 'viewer' as const,
      provider: null, email: null, avatar_url: null, is_approved: 1,
      workspace_id: 1, tenant_id: 1, created_at: 1000, updated_at: 1000,
      last_login_at: null, session_id: 1,
    }
    mockGet.mockReturnValue(row)
    const result = validateSession('some-token')
    expect(result!.provider).toBe('local')
  })
})

// ── destroySession ───────────────────────────────────────────────────────────
describe('destroySession', () => {
  beforeEach(() => { vi.clearAllMocks(); mockGet.mockReturnValue({ count: 1 }) })

  it('executes DELETE on user_sessions', () => {
    destroySession('abc123')
    expect(mockRun).toHaveBeenCalled()
  })
})

// ── destroyAllUserSessions ───────────────────────────────────────────────────
describe('destroyAllUserSessions', () => {
  beforeEach(() => { vi.clearAllMocks(); mockGet.mockReturnValue({ count: 1 }) })

  it('executes DELETE by user_id', () => {
    destroyAllUserSessions(7)
    expect(mockRun).toHaveBeenCalled()
  })
})

// ── getUserById ──────────────────────────────────────────────────────────────
describe('getUserById', () => {
  beforeEach(() => { vi.clearAllMocks() })

  it('returns null when row not found', () => {
    mockGet.mockReturnValue(undefined)
    expect(getUserById(99)).toBeNull()
  })

  it('returns user object when row found', () => {
    const user = makeUser({ id: 7, username: 'alice' })
    mockGet.mockReturnValue(user)
    const result = getUserById(7)
    expect(result).not.toBeNull()
    expect(result!.username).toBe('alice')
  })

  it('preserves existing tenant_id from joined workspace', () => {
    const user = makeUser({ tenant_id: 5 })
    mockGet.mockReturnValue(user)
    const result = getUserById(1)
    expect(result!.tenant_id).toBe(5)
  })
})

// ── createUser ───────────────────────────────────────────────────────────────
describe('createUser', () => {
  beforeEach(() => {
    vi.clearAllMocks()
    mockGet.mockReturnValue(makeUser())
  })

  it('throws when password is shorter than 12 characters', () => {
    expect(() => createUser('alice', 'short', 'Alice')).toThrow(
      'Password must be at least 12 characters'
    )
  })

  it('inserts and returns user for valid input', () => {
    const result = createUser('alice', 'long-enough-password', 'Alice', 'operator')
    expect(mockRun).toHaveBeenCalled()
    expect(result).toBeDefined()
    expect(result.username).toBe('testuser') // mockGet returns the fixture
  })

  it('uses "operator" as default role', () => {
    createUser('bob', 'long-enough-password', 'Bob')
    const runCall = mockRun.mock.calls[0] as unknown[]
    // role is the 4th positional param in the INSERT
    expect(runCall[3]).toBe('operator')
  })

  it('accepts admin role override', () => {
    createUser('admin2', 'long-enough-password', 'Admin2', 'admin')
    const runCall = mockRun.mock.calls[0] as unknown[]
    expect(runCall[3]).toBe('admin')
  })
})

// ── updateUser ───────────────────────────────────────────────────────────────
describe('updateUser', () => {
  beforeEach(() => {
    vi.clearAllMocks()
    mockGet.mockReturnValue(makeUser())
  })

  it('returns user unchanged when no update fields provided', () => {
    const result = updateUser(1, {})
    // No run() call should happen — returns getUserById directly
    expect(result).toBeDefined()
    expect(mockRun).not.toHaveBeenCalled()
  })

  it('updates display_name', () => {
    updateUser(1, { display_name: 'New Name' })
    expect(mockRun).toHaveBeenCalled()
  })

  it('hashes password when password update is requested', () => {
    updateUser(1, { password: 'new-long-password' })
    const runCall = mockRun.mock.calls[0] as unknown[]
    expect(runCall[0]).toBe('hashed:new-long-password')
  })

  it('updates role', () => {
    updateUser(1, { role: 'viewer' })
    expect(mockRun).toHaveBeenCalled()
  })
})

// ── deleteUser ───────────────────────────────────────────────────────────────
describe('deleteUser', () => {
  beforeEach(() => {
    vi.clearAllMocks()
    mockGet.mockReturnValue({ count: 1 })
  })

  it('returns true when user was deleted', () => {
    mockRun.mockReturnValue({ lastInsertRowid: 0, changes: 1 })
    const result = deleteUser(1)
    expect(result).toBe(true)
  })

  it('returns false when user did not exist', () => {
    mockRun.mockReturnValue({ lastInsertRowid: 0, changes: 0 })
    const result = deleteUser(999)
    expect(result).toBe(false)
  })
})

// ── registerAuthResolver ─────────────────────────────────────────────────────
describe('registerAuthResolver', () => {
  const origEnv = { ...process.env }

  afterEach(() => {
    process.env = { ...origEnv }
    // Reset the hook by registering a null-returning one
    registerAuthResolver(() => null)
    vi.clearAllMocks()
  })

  it('custom resolver is invoked when API key is present but not matched otherwise', () => {
    const customUser = makeUser({ username: 'plugin-user', role: 'admin' })
    registerAuthResolver((key: string) => key === 'custom-key' ? customUser : null)

    // Ensure default API_KEY does not match so resolver gets a chance
    process.env.API_KEY = ''
    // mock DB to return no settings override and no agent key
    mockGet.mockReturnValue(undefined)
    mockAll.mockReturnValue([])

    const req = makeRequest({ 'x-api-key': 'custom-key' })
    const result = getUserFromRequest(req)
    expect(result).not.toBeNull()
    expect(result!.username).toBe('plugin-user')
  })

  it('custom resolver returning null does not authenticate', () => {
    registerAuthResolver(() => null)
    process.env.API_KEY = ''
    mockGet.mockReturnValue(undefined)

    const req = makeRequest({ 'x-api-key': 'any-key' })
    const result = getUserFromRequest(req)
    expect(result).toBeNull()
  })
})

// ── getUserFromRequest ───────────────────────────────────────────────────────
describe('getUserFromRequest', () => {
  const origEnv = { ...process.env }

  beforeEach(() => {
    vi.clearAllMocks()
    process.env = { ...origEnv, API_KEY: '' }
    mockGet.mockReturnValue(undefined)
    // reset plugin hook
    registerAuthResolver(() => null)
  })

  afterEach(() => {
    process.env = { ...origEnv }
  })

  it('returns null when no auth mechanism is present', () => {
    expect(getUserFromRequest(makeRequest())).toBeNull()
  })

  it('authenticates via session cookie', () => {
    const sessionRow = {
      id: 3, username: 'cookie-user', display_name: 'Cookie', role: 'operator' as const,
      provider: 'local' as const, email: null, avatar_url: null, is_approved: 1,
      workspace_id: 1, tenant_id: 1, created_at: 0, updated_at: 0, last_login_at: null,
      session_id: 55,
    }
    // WHY: In getUserFromRequest, the session cookie path fires BEFORE the API key
    // path — so the validateSession DB query (JOIN on user_sessions) is call #1,
    // and resolveActiveApiKey's settings lookup is never reached if session succeeds.
    // The workspace/tenant fallback calls happen inside validateSession's return path.
    mockGet
      .mockReturnValueOnce(sessionRow)           // (1) validateSession JOIN query
      .mockReturnValue({ id: 1, tenant_id: 1 }) // (2+) workspace/tenant fallback

    const req = makeRequest({ cookie: 'mc_session=valid-session-token' })
    const result = getUserFromRequest(req)
    expect(result).not.toBeNull()
    expect(result!.username).toBe('cookie-user')
  })

  it('authenticates via x-api-key header matching API_KEY env var', () => {
    process.env.API_KEY = 'my-secret-api-key'
    // settings DB lookup returns nothing → falls back to env
    mockGet.mockReturnValue(undefined)

    const req = makeRequest({ 'x-api-key': 'my-secret-api-key' })
    const result = getUserFromRequest(req)
    expect(result).not.toBeNull()
    expect(result!.username).toBe('api')
    expect(result!.role).toBe('admin')
  })

  it('authenticates via Authorization Bearer header', () => {
    process.env.API_KEY = 'bearer-key'
    mockGet.mockReturnValue(undefined)

    const req = makeRequest({ authorization: 'Bearer bearer-key' })
    const result = getUserFromRequest(req)
    expect(result).not.toBeNull()
    expect(result!.username).toBe('api')
  })

  it('rejects mismatched API key', () => {
    process.env.API_KEY = 'correct-key'
    mockGet.mockReturnValue(undefined)

    const req = makeRequest({ 'x-api-key': 'wrong-key' })
    const result = getUserFromRequest(req)
    expect(result).toBeNull()
  })

  it('attaches agent_name from x-agent-name header', () => {
    process.env.API_KEY = 'key'
    mockGet.mockReturnValue(undefined)

    const req = makeRequest({ 'x-api-key': 'key', 'x-agent-name': 'ultron' })
    const result = getUserFromRequest(req)
    expect(result).not.toBeNull()
    expect(result!.agent_name).toBe('ultron')
  })

  it('returns null for empty x-agent-name (whitespace)', () => {
    // agent_name should be null when header is blank
    process.env.API_KEY = 'key'
    mockGet.mockReturnValue(undefined)

    const req = makeRequest({ 'x-api-key': 'key', 'x-agent-name': '   ' })
    const result = getUserFromRequest(req)
    expect(result!.agent_name).toBeNull()
  })

  it('uses settings DB override for API key over env var', () => {
    process.env.API_KEY = 'env-key'
    // First call: settings lookup returns DB override key
    mockGet.mockReturnValueOnce({ value: 'db-override-key' })

    const req = makeRequest({ 'x-api-key': 'db-override-key' })
    const result = getUserFromRequest(req)
    expect(result).not.toBeNull()
    expect(result!.username).toBe('api')
  })
})

// ── safeCompare (re-validate on Unicode edge cases) ──────────────────────────
describe('safeCompare — Unicode and binary edge cases', () => {
  it('handles multi-byte Unicode characters consistently', () => {
    const emoji = '🔐secret'
    expect(safeCompare(emoji, emoji)).toBe(true)
    expect(safeCompare(emoji, '🔐secre')).toBe(false)
  })

  it('is case-sensitive', () => {
    expect(safeCompare('Admin', 'admin')).toBe(false)
  })

  it('handles strings with special SQL characters', () => {
    const sql = "'; DROP TABLE users; --"
    expect(safeCompare(sql, sql)).toBe(true)
  })
})

// ── requireRole ───────────────────────────────────────────────────────────────
describe('requireRole', () => {
  beforeEach(() => {
    vi.clearAllMocks()
    // Default: no DB overrides, settings returns nothing
    mockGet.mockReturnValue(undefined)
    delete process.env.API_KEY
    // Reset any resolver from previous tests
    registerAuthResolver(null as any)
  })

  it('returns 401 when no user is authenticated', () => {
    const req = new Request('http://localhost/')
    const result = requireRole(req, 'viewer')
    expect(result.status).toBe(401)
    expect(result.error).toMatch(/Authentication required/i)
  })

  it('returns 403 when authenticated user has insufficient role', () => {
    // WHY: registerAuthResolver is the hook called AFTER env key check fails.
    // It receives (apiKey, agentName) and returns a User or null.
    // Register a resolver that returns a viewer for any key, then require 'operator' → 403.
    registerAuthResolver((_apiKey: string, _agentName: string | null) => ({
      id: 99,
      username: 'viewer-user',
      display_name: 'Viewer',
      role: 'viewer' as const,
      workspace_id: 1,
      tenant_id: 1,
      created_at: 0,
      updated_at: 0,
      last_login_at: null,
      is_approved: 1 as const,
      auth_provider: null,
      agent_name: null,
    }))

    const req = new Request('http://localhost/', { headers: { 'x-api-key': 'some-key' } })
    const result = requireRole(req, 'operator')
    expect(result.status).toBe(403)
    expect(result.error).toMatch(/operator/i)
  })

  it('returns the user when role is met or exceeded', () => {
    // Admin env key → role 'admin', require 'admin' → passes
    process.env.API_KEY = 'admin-key'
    mockGet.mockReturnValue(undefined) // no DB override
    const req = new Request('http://localhost/', { headers: { 'x-api-key': 'admin-key' } })
    const result = requireRole(req, 'admin')
    expect(result.status).toBeUndefined()
    expect(result.user).toBeDefined()
    expect(result.user!.role).toBe('admin')
  })
})

// ── agent API key DB path (parseAgentScopes + deriveRoleFromScopes) ──────────
describe('getUserFromRequest — agent API key DB path', () => {
  const NOW_SEC = Math.floor(Date.now() / 1000)

  beforeEach(() => {
    vi.clearAllMocks()
    // WHY: default undefined so resolveActiveApiKey returns null (no configured key),
    // forcing the agent_api_keys DB lookup path. { count: 1 } would be treated as
    // a truthy configured key row, corrupting the mock call sequence.
    mockGet.mockReturnValue(undefined)
    delete process.env.API_KEY
    registerAuthResolver(null as any)
  })

  function makeAgentKeyRequest(key: string): Request {
    return new Request('http://localhost/', { headers: { 'x-api-key': key } })
  }

  // Mock call order for agent key path (DB already initialized, no seed check):
  // (1) resolveActiveApiKey → settings.get('api_key') → undefined (no override)
  // (2) agent_api_keys.get(keyHash) → agentKeyRow
  // (3) agents.get(agent_id, workspace_id) → agentRow  (only if row passes validity check)
  // (4) agent_api_keys UPDATE last_used_at → mockRun (not mockGet)
  // (5) getDefaultWorkspaceContext workspace.get(1) → { id: 1, tenant_id: 1 }

  it('derives admin role from agent scopes containing "admin"', () => {
    const agentKeyRow = {
      id: 5, agent_id: 10, workspace_id: 1,
      scopes: JSON.stringify(['admin', 'read']),
      expires_at: null, revoked_at: null,
    }
    const agentRow = { id: 10, name: 'super-agent' }

    mockGet
      .mockReturnValueOnce(undefined)           // (1) resolveActiveApiKey → no override
      .mockReturnValueOnce(agentKeyRow)         // (2) agent_api_keys
      .mockReturnValueOnce(agentRow)            // (3) agents
      .mockReturnValue({ id: 1, tenant_id: 1 }) // (5+) workspace context

    const user = getUserFromRequest(makeAgentKeyRequest('any-raw-key'))
    expect(user).not.toBeNull()
    expect(user!.role).toBe('admin')
    expect(user!.username).toBe('agent:super-agent')
  })

  it('derives operator role from agent scopes containing "operator"', () => {
    const agentKeyRow = {
      id: 6, agent_id: 11, workspace_id: 1,
      scopes: JSON.stringify(['operator']),
      expires_at: null, revoked_at: null,
    }
    const agentRow = { id: 11, name: 'ops-agent' }

    mockGet
      .mockReturnValueOnce(undefined)
      .mockReturnValueOnce(agentKeyRow)
      .mockReturnValueOnce(agentRow)
      .mockReturnValue({ id: 1, tenant_id: 1 })

    const user = getUserFromRequest(makeAgentKeyRequest('op-key'))
    expect(user).not.toBeNull()
    expect(user!.role).toBe('operator')
  })

  it('defaults to viewer role when no recognized scopes present', () => {
    const agentKeyRow = {
      id: 7, agent_id: 12, workspace_id: 1,
      scopes: JSON.stringify(['read', 'tasks:write']),
      expires_at: null, revoked_at: null,
    }
    const agentRow = { id: 12, name: 'readonly-agent' }

    mockGet
      .mockReturnValueOnce(undefined)
      .mockReturnValueOnce(agentKeyRow)
      .mockReturnValueOnce(agentRow)
      .mockReturnValue({ id: 1, tenant_id: 1 })

    const user = getUserFromRequest(makeAgentKeyRequest('ro-key'))
    expect(user).not.toBeNull()
    expect(user!.role).toBe('viewer')
  })

  it('returns null when agent API key is expired', () => {
    const expiredKeyRow = {
      id: 8, agent_id: 13, workspace_id: 1,
      scopes: '[]',
      expires_at: NOW_SEC - 3600, // expired 1 hour ago
      revoked_at: null,
    }

    mockGet
      .mockReturnValueOnce(undefined)    // resolveActiveApiKey
      .mockReturnValueOnce(expiredKeyRow) // agent_api_keys

    const user = getUserFromRequest(makeAgentKeyRequest('expired-key'))
    expect(user).toBeNull()
  })

  it('returns null when agent API key is revoked', () => {
    const revokedKeyRow = {
      id: 9, agent_id: 14, workspace_id: 1,
      scopes: '["admin"]',
      expires_at: null,
      revoked_at: NOW_SEC - 60, // revoked 1 min ago
    }

    mockGet
      .mockReturnValueOnce(undefined)     // resolveActiveApiKey
      .mockReturnValueOnce(revokedKeyRow) // agent_api_keys

    const user = getUserFromRequest(makeAgentKeyRequest('revoked-key'))
    expect(user).toBeNull()
  })

  it('handles invalid JSON scopes gracefully (defaults to viewer)', () => {
    const agentKeyRow = {
      id: 10, agent_id: 15, workspace_id: 1,
      scopes: 'NOT_JSON',
      expires_at: null, revoked_at: null,
    }
    const agentRow = { id: 15, name: 'bad-scopes-agent' }

    mockGet
      .mockReturnValueOnce(undefined)
      .mockReturnValueOnce(agentKeyRow)
      .mockReturnValueOnce(agentRow)
      .mockReturnValue({ id: 1, tenant_id: 1 })

    const user = getUserFromRequest(makeAgentKeyRequest('bad-scopes-key'))
    expect(user).not.toBeNull()
    // Invalid JSON → parseAgentScopes returns empty Set → deriveRoleFromScopes → 'viewer'
    expect(user!.role).toBe('viewer')
  })

  it('returns null when x-agent-name does not match the key owner and no admin scope', () => {
    // WHY: covers lines 469-470 — agent name mismatch with non-admin key is rejected
    const agentKeyRow = {
      id: 20, agent_id: 25, workspace_id: 1,
      scopes: JSON.stringify(['read']),  // NOT admin
      expires_at: null, revoked_at: null,
    }
    const agentRow = { id: 25, name: 'jarvis' }

    mockGet
      .mockReturnValueOnce(undefined)
      .mockReturnValueOnce(agentKeyRow)
      .mockReturnValueOnce(agentRow)
      .mockReturnValue({ id: 1, tenant_id: 1 })

    // x-agent-name header claims to be 'ultron' but the key belongs to 'jarvis'
    const req = new Request('http://localhost/', {
      headers: { 'x-api-key': 'mismatch-key', 'x-agent-name': 'ultron' },
    })
    const user = getUserFromRequest(req)
    expect(user).toBeNull()
  })

  it('falls back gracefully when agent_api_keys query throws', () => {
    // WHY: covers line 490 catch block — any DB error in agent key path is silently ignored
    // to prevent auth from crashing on startup race / missing table.
    mockPrepare.mockImplementationOnce(() => {
      // resolveActiveApiKey's prepare call returns normally
      return { run: mockRun, get: vi.fn(() => undefined), all: mockAll }
    })
    mockPrepare.mockImplementationOnce(() => {
      // agent_api_keys prepare call throws
      throw new Error('SQLITE_ERROR: no such table: agent_api_keys')
    })

    const user = getUserFromRequest(makeAgentKeyRequest('any-key'))
    // Should return null (fell through all auth methods), not throw
    expect(user).toBeNull()
  })

  it('returns null when Authorization header uses an unrecognized scheme', () => {
    // WHY: covers lines 533-534 — extractApiKeyFromHeaders returns null for non-bearer schemes
    mockGet.mockReturnValue(undefined)
    const req = new Request('http://localhost/', {
      headers: { authorization: 'Basic dXNlcjpwYXNz' },
    })
    const user = getUserFromRequest(req)
    // Basic auth is not accepted — no API key extracted → null
    expect(user).toBeNull()
  })
})
