/**
 * Unit tests for db.ts core functions.
 * WHY: The existing db-helpers.test.ts covers db_helpers but leaves validateRequiredEnv,
 * needsFirstTimeSetup, closeDatabase, logAuditEvent, and appendProvisionEvent untested.
 * This file fills that gap without duplicating helper tests.
 */
import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest'

// Use vi.hoisted so mock variables are available inside vi.mock() factories
const { mockPragma, mockPrepare, mockRun, mockGet, mockBroadcast } = vi.hoisted(() => {
  const mockRun = vi.fn(() => ({ lastInsertRowid: 99, changes: 1 }))
  const mockGet = vi.fn((): any => ({ count: 0 }))
  const mockPrepare = vi.fn(() => ({ run: mockRun, get: mockGet, all: vi.fn(() => []) }))
  const mockPragma = vi.fn()
  const mockBroadcast = vi.fn()
  return { mockPragma, mockPrepare, mockRun, mockGet, mockBroadcast }
})

vi.mock('better-sqlite3', () => ({
  default: vi.fn(() => ({
    pragma: mockPragma,
    prepare: mockPrepare,
    exec: vi.fn(),
    close: vi.fn(),
  })),
}))

vi.mock('@/lib/config', () => ({
  config: { dbPath: ':memory:' },
  ensureDirExists: vi.fn(),
}))

vi.mock('@/lib/migrations', () => ({ runMigrations: vi.fn() }))

vi.mock('@/lib/password', () => ({
  hashPassword: vi.fn((p: string) => `hashed:${p}`),
}))

vi.mock('@/lib/logger', () => ({
  logger: { info: vi.fn(), error: vi.fn(), warn: vi.fn(), debug: vi.fn() },
}))

vi.mock('@/lib/event-bus', () => ({
  eventBus: { broadcast: mockBroadcast, on: vi.fn(), emit: vi.fn() },
}))

vi.mock('@/lib/auto-credentials', () => ({
  ensureAutoGeneratedCredentials: vi.fn(),
}))

vi.mock('@/lib/seeds/ecc-instincts', () => ({
  seedECCInstincts: vi.fn(),
}))

vi.mock('@/lib/webhooks', () => ({
  initWebhookListener: vi.fn(),
}))

vi.mock('@/lib/scheduler', () => ({
  initScheduler: vi.fn(),
}))

// Import after all mocks are registered
import {
  validateRequiredEnv,
  needsFirstTimeSetup,
  closeDatabase,
  logAuditEvent,
  appendProvisionEvent,
  resolveSeedAuthPassword,
  db_helpers,
} from '@/lib/db'
import { logger } from '@/lib/logger'

const mockLogger = logger as unknown as {
  info: ReturnType<typeof vi.fn>
  error: ReturnType<typeof vi.fn>
  warn: ReturnType<typeof vi.fn>
  debug: ReturnType<typeof vi.fn>
}

// ────────────────────────────────────────────────────────────────────────────
// validateRequiredEnv
// ────────────────────────────────────────────────────────────────────────────
describe('validateRequiredEnv', () => {
  const origEnv = { ...process.env }

  afterEach(() => {
    process.env = { ...origEnv }
    vi.clearAllMocks()
  })

  it('warns when neither AUTH_PASS nor AUTH_PASS_B64 is set', () => {
    process.env.AUTH_PASS = ''
    process.env.AUTH_PASS_B64 = ''
    validateRequiredEnv()
    expect(mockLogger.warn).toHaveBeenCalledWith(
      expect.stringContaining('AUTH_PASS')
    )
  })

  it('does not warn when AUTH_PASS is set', () => {
    process.env.AUTH_PASS = 'strong-password-here'
    process.env.AUTH_PASS_B64 = ''
    validateRequiredEnv()
    // warn may still be called for other reasons but not for missing auth pass
    const calls: string[] = mockLogger.warn.mock.calls.map((c: any[]) => String(c[0]))
    const authWarn = calls.some((msg) => msg.includes('Neither AUTH_PASS'))
    expect(authWarn).toBe(false)
  })

  it('does not warn when AUTH_PASS_B64 is set', () => {
    process.env.AUTH_PASS = ''
    process.env.AUTH_PASS_B64 = Buffer.from('secure-pass').toString('base64')
    validateRequiredEnv()
    const calls: string[] = mockLogger.warn.mock.calls.map((c: any[]) => String(c[0]))
    const authWarn = calls.some((msg) => msg.includes('Neither AUTH_PASS'))
    expect(authWarn).toBe(false)
  })

  it('warns when MISSION_CONTROL_DB_PATH directory does not exist', () => {
    process.env.MISSION_CONTROL_DB_PATH = '/absolutely/nonexistent/path/db.sqlite'
    validateRequiredEnv()
    expect(mockLogger.warn).toHaveBeenCalledWith(
      expect.stringContaining('does not exist')
    )
  })
})

// ────────────────────────────────────────────────────────────────────────────
// needsFirstTimeSetup
// ────────────────────────────────────────────────────────────────────────────
describe('needsFirstTimeSetup', () => {
  beforeEach(() => {
    vi.clearAllMocks()
  })

  it('returns true when user count is 0', () => {
    mockGet.mockReturnValueOnce({ count: 0 })
    expect(needsFirstTimeSetup()).toBe(true)
  })

  it('returns false when users exist', () => {
    mockGet.mockReturnValueOnce({ count: 3 })
    expect(needsFirstTimeSetup()).toBe(false)
  })

  it('returns false on database error (safe fallback)', () => {
    mockPrepare.mockImplementationOnce(() => {
      throw new Error('SQLITE_ERROR: no such table: users')
    })
    expect(needsFirstTimeSetup()).toBe(false)
  })
})

// ────────────────────────────────────────────────────────────────────────────
// closeDatabase
// ────────────────────────────────────────────────────────────────────────────
describe('closeDatabase', () => {
  beforeEach(() => {
    vi.clearAllMocks()
  })

  it('is idempotent — calling it multiple times does not throw', () => {
    expect(() => {
      closeDatabase()
      closeDatabase()
    }).not.toThrow()
  })
})

// ────────────────────────────────────────────────────────────────────────────
// logAuditEvent
// ────────────────────────────────────────────────────────────────────────────
describe('logAuditEvent', () => {
  beforeEach(() => {
    vi.clearAllMocks()
    mockGet.mockReturnValue({ count: 1 })
  })

  it('inserts an audit record with all fields', () => {
    logAuditEvent({
      action: 'user_created',
      actor: 'admin',
      actor_id: 1,
      target_type: 'user',
      target_id: 42,
      detail: { email: 'test@example.com' },
      ip_address: '127.0.0.1',
      user_agent: 'Mozilla/5.0',
    })

    expect(mockRun).toHaveBeenCalledWith(
      'user_created',
      'admin',
      1,
      'user',
      42,
      JSON.stringify({ email: 'test@example.com' }),
      '127.0.0.1',
      'Mozilla/5.0',
    )
  })

  it('inserts null for optional fields when omitted', () => {
    logAuditEvent({ action: 'config_changed', actor: 'system' })

    expect(mockRun).toHaveBeenCalledWith(
      'config_changed',
      'system',
      null,
      null,
      null,
      null,
      null,
      null,
    )
  })

  it('broadcasts audit.security for security-sensitive actions', () => {
    const securityActions = ['login_failed', 'user_created', 'user_deleted', 'password_change']
    for (const action of securityActions) {
      vi.clearAllMocks()
      mockGet.mockReturnValue({ count: 1 })
      logAuditEvent({ action, actor: 'system' })
      expect(mockBroadcast).toHaveBeenCalledWith(
        'audit.security',
        expect.objectContaining({ action }),
      )
    }
  })

  it('does NOT broadcast for non-security actions', () => {
    logAuditEvent({ action: 'config_changed', actor: 'admin' })
    expect(mockBroadcast).not.toHaveBeenCalledWith('audit.security', expect.anything())
  })

  it('includes timestamp in broadcast payload', () => {
    const before = Math.floor(Date.now() / 1000)
    logAuditEvent({ action: 'login_failed', actor: 'hacker' })
    const after = Math.floor(Date.now() / 1000)

    const broadcastCall = mockBroadcast.mock.calls.find(
      (c: any[]) => c[0] === 'audit.security'
    )
    expect(broadcastCall).toBeDefined()
    const payload = broadcastCall![1] as { timestamp: number }
    expect(payload.timestamp).toBeGreaterThanOrEqual(before)
    expect(payload.timestamp).toBeLessThanOrEqual(after)
  })
})

// ────────────────────────────────────────────────────────────────────────────
// appendProvisionEvent
// ────────────────────────────────────────────────────────────────────────────
describe('appendProvisionEvent', () => {
  beforeEach(() => {
    vi.clearAllMocks()
    mockGet.mockReturnValue({ count: 1 })
  })

  it('inserts event with provided fields', () => {
    appendProvisionEvent({
      job_id: 7,
      level: 'warn',
      step_key: 'install-deps',
      message: 'apt-get returned warnings',
      data: { code: 1 },
    })

    expect(mockRun).toHaveBeenCalledWith(
      7,
      'warn',
      'install-deps',
      'apt-get returned warnings',
      JSON.stringify({ code: 1 }),
    )
  })

  it('defaults level to "info" when not provided', () => {
    appendProvisionEvent({ job_id: 3, message: 'Step started' })

    expect(mockRun).toHaveBeenCalledWith(3, 'info', null, 'Step started', null)
  })

  it('passes null for step_key and data when omitted', () => {
    appendProvisionEvent({ job_id: 5, level: 'error', message: 'Failed' })

    expect(mockRun).toHaveBeenCalledWith(5, 'error', null, 'Failed', null)
  })

  it('stringifies data object', () => {
    const data = { key: 'value', count: 3 }
    appendProvisionEvent({ job_id: 1, message: 'done', data })

    expect(mockRun).toHaveBeenCalledWith(1, 'info', null, 'done', JSON.stringify(data))
  })
})

// ────────────────────────────────────────────────────────────────────────────
// db_helpers.getTaskSubscribers
// ────────────────────────────────────────────────────────────────────────────
describe('db_helpers.getTaskSubscribers', () => {
  beforeEach(() => {
    vi.clearAllMocks()
    mockGet.mockReturnValue({ count: 1 })
  })

  it('returns agent names for subscribed agents', () => {
    const rows = [{ agent_name: 'jarvis' }, { agent_name: 'aegis' }]
    mockPrepare.mockImplementationOnce(() => ({ run: mockRun, get: mockGet, all: vi.fn(() => rows) }))

    const result = db_helpers.getTaskSubscribers(1, 1)
    expect(result).toEqual(['jarvis', 'aegis'])
  })

  it('returns empty array when no subscribers', () => {
    mockPrepare.mockImplementationOnce(() => ({ run: mockRun, get: mockGet, all: vi.fn(() => []) }))

    const result = db_helpers.getTaskSubscribers(99, 1)
    expect(result).toEqual([])
  })

  it('uses workspace_id=1 as default when not provided', () => {
    const allSpy = vi.fn(() => [{ agent_name: 'ultron' }])
    mockPrepare.mockImplementationOnce(() => ({ run: mockRun, get: mockGet, all: allSpy }))

    const result = db_helpers.getTaskSubscribers(7)
    expect(result).toEqual(['ultron'])
    // Verify workspace_id default was applied (second arg to all())
    expect(allSpy).toHaveBeenCalledWith(7, 1)
  })
})

// ────────────────────────────────────────────────────────────────────────────
// db_helpers.ensureTaskSubscription
// ────────────────────────────────────────────────────────────────────────────
describe('db_helpers.ensureTaskSubscription', () => {
  beforeEach(() => {
    vi.clearAllMocks()
    mockGet.mockReturnValue({ count: 1 })
  })

  it('inserts subscription via INSERT OR IGNORE', () => {
    db_helpers.ensureTaskSubscription(10, 'jarvis', 1)
    expect(mockRun).toHaveBeenCalledWith('jarvis', 10, 1)
  })

  it('returns early without DB call when agentName is empty', () => {
    db_helpers.ensureTaskSubscription(10, '', 1)
    // Empty agentName guard at top of function — run() should NOT be called
    expect(mockRun).not.toHaveBeenCalled()
  })

  it('uses workspace_id=1 as default', () => {
    db_helpers.ensureTaskSubscription(5, 'aegis')
    expect(mockRun).toHaveBeenCalledWith('aegis', 5, 1)
  })
})

// ────────────────────────────────────────────────────────────────────────────
// resolveSeedAuthPassword — additional edge cases beyond db-seed-auth-pass.test
// ────────────────────────────────────────────────────────────────────────────
describe('resolveSeedAuthPassword — edge cases', () => {
  it('returns null when AUTH_PASS_B64 is whitespace only', () => {
    const result = resolveSeedAuthPassword({
      AUTH_PASS_B64: '   ',
    } as unknown as NodeJS.ProcessEnv)
    expect(result).toBeNull()
  })

  it('falls back to AUTH_PASS when AUTH_PASS_B64 decodes to empty string', () => {
    // An empty string base64-encodes to "" which has 0 length after decode
    const emptyB64 = Buffer.from('', 'utf8').toString('base64') // ""
    const result = resolveSeedAuthPassword({
      AUTH_PASS_B64: emptyB64,
      AUTH_PASS: 'fallback',
    } as unknown as NodeJS.ProcessEnv)
    // Empty encoded string → decoded is empty → falls through to AUTH_PASS
    expect(result).toBe('fallback')
  })

  it('returns decoded value when AUTH_PASS_B64 is valid and non-empty', () => {
    const encoded = Buffer.from('MyStr0ngP@ssword!', 'utf8').toString('base64')
    const result = resolveSeedAuthPassword({
      AUTH_PASS_B64: encoded,
    } as unknown as NodeJS.ProcessEnv)
    expect(result).toBe('MyStr0ngP@ssword!')
  })
})
